# STMGT cross-machine setup template
meta:
  version: "1.0"
  updated: "2025-11-01"
  description: Template for onboarding new workstations or virtual machines.

environment:
  conda_env: dsp
  python_version: "3.10"
  environment_file: environment.yml
  requirements_file: requirements.txt
  post_install_commands:
    - conda run -n dsp pip install -e .
  streamlit_port: 8505
  fastapi_port: 8000

files:
  env_file: .env
  env_template: .env.example
  scheduler_config: configs/project_config.yaml
  training_config_dir: configs/
  dashboard_entrypoint: run_dashboard.sh
  training_entrypoint: scripts/training/train_stmgt.py
  data_collection_script: scripts/data/collect_and_render.py

paths:
  project_root: "."
  cache_dir: cache
  data_dir: data
  processed_data_dir: data/processed
  runs_dir: data/runs
  outputs_dir: outputs
  models_dir: models/training_runs
  logs_dir: logs
  temp_dir: cache/tmp

artifacts:
  dashboard_history: outputs/stmgt_v2_*
  training_history_csv: outputs/**/training_history.csv
  realtime_stats_cache: cache/realtime_stats.json

secrets:
  required_env_vars:
    - name: GOOGLE_MAPS_API_KEY
      description: Google Maps Directions API key with traffic data access.
    - name: OPENMETEO_BASE_URL
      default: https://api.open-meteo.com/v1/forecast
    - name: OVERPASS_URL
      default: https://overpass-api.de/api/interpreter
    - name: TZ
      default: Asia/Ho_Chi_Minh
  optional_env_vars:
    - name: PROJECT_ENV
      default: production
    - name: STREAMLIT_SERVER_PORT
      default: "8505"
    - name: ENABLE_MONITORING
      default: "true"

remote:
  enabled: false
  host: ""
  username: ""
  repo_path: ""
  data_mount: ""
  notes:
    - Enable when deploying to cloud or remote VM.
    - Scripts under scripts/deployment/ assume SSH access.
    - Configure SSH keys before toggling this section.

validation:
  prechecks:
    - conda --version
    - git --version
  smoke_tests:
    - conda run -n dsp pytest -k smoke --maxfail=1
    - conda run -n dsp streamlit version
