visualize:
  nodes_map:
    figsize: [10, 8]
    s: 1
    alpha: 0.5
    color: blue
    label: Nodes
    title: Traffic Nodes in HCMC
    xlabel: Longitude
    ylabel: Latitude
    save_path: data/nodes_map.png
    limit_nodes: 10000 # Limit for performance

  traffic_heatmap:
    figsize: [10, 8]
    s: 5
    alpha: 0.7
    cmap: RdYlGn_r
    title: Traffic Speed Heatmap
    xlabel: Longitude
    ylabel: Latitude
    save_path: data/traffic_heatmap.png

  events_map:
    figsize: [10, 8]
    node_s: 1
    node_alpha: 0.3
    node_color: blue
    event_s: 100
    event_color: red
    event_marker: x
    title: Events and Nodes
    xlabel: Longitude
    ylabel: Latitude
    save_path: data/events_map.png
